{{- if not .Values.service.spec.network.internal -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bci-services-provider.fullname" . }}
  labels:
    {{- include "bci-services-provider.labels" . | nindent 4 }}
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /{{.Values.service.metadata.version}}/{{.Values.service.metadata.name}}
        pathType: Prefix
        backend:
          service:
            name: {{ include "bci-services-provider.fullname" . }}-{{.Values.service.metadata.version}}-service
            port:
              number: 80
{{- end }}
