{{- if .Values.service.spec.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bci-services-provider.serviceAccountName" . }}
  labels:
    {{- include "bci-services-provider.labels" . | nindent 4 }}
  {{- with .Values.service.spec.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.service.spec.security.serviceAccount.automount }}
{{- end }}
