apiVersion: v1
kind: Service
metadata:
  name: {{ include "bci-services-provider.fullname" . }}-{{.Values.service.metadata.version}}-service
  labels:
    {{- include "bci-services-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.spec.network.type }}
  ports:
    - port: {{ .Values.service.spec.network.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bci-services-provider.selectorLabels" . | nindent 4 }}